env: 
  - DOMAIN=$s3_domain
  - BUCKET=$s3_bucket

if: branch = develop
  env: 
    - DOMAIN=$s3_domain_develop
    - BUCKET=$s3_bucket_develop

language: node_js
node_js:
  - '8'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test:headless

before_deploy:
  - yarn build --prod --aot --base-href $s3_domain

deploy:
  provider: s3
  access_key_id: $s3_access_key_id
  secret_access_key:
    secure: $s3_secret_access_key
  bucket: $s3_bucket
  acl: public_read
  skip_cleanup: true
  local_dir: dist/shoppingList
  region: $s3_region
  on:
    branch: master
