language: node_js
env:
  global:
    - GET_ENV_VAR=./travis_get_variables.sh
    - AWS_ENV=$($GET_ENV_VAR $s3_domain_develop $s3_domain)
    - AWS_BUCKET=$($GET_ENV_VAR $s3_bucket_develop $s3_bucket)
node_js:
  - '8'

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test:headless

before_deploy:
  - yarn build --prod --aot --base-href $AWS_ENV

deploy:
  provider: s3
  access_key_id: $s3_access_key_id
  secret_access_key:
    secure: $s3_secret_access_key
  bucket: $AWS_BUCKET
  acl: public_read
  local_dir: dist/shoppingList
  region: $s3_region
  on:
    all_branches: true
