language: node_js
env:
  global:
    - GET_ENV_VAR=./travis_get_variables.sh
    - AWS_ENV=$($GET_ENV_VAR $s3_domain_develop $s3_domain)
    - AWS_BUCKET=$($GET_ENV_VAR $s3_bucket_develop $s3_bucket)
node_js:
  - '8'

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  - FOLDER=./
  - FOLDER=./api

cache:
  yarn: true
  directories:
    - node_modules

script:
  - cd $FOLDER

install:
  - yarn

script:
  - if [ $FOLDER == "./api" ]; then yarn test; else yarn test:headless fi
  - yarn deploy;

env:
  global: 
    after_sucess:
      - docker-compose build;
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $REGISTRY;
      - docker-compose push;
