language: node_js
node_js:
  - '8'

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  - PROJECT='app'
  - PROJECT='api'

before_install:
  - if [ $PROJECT == 'api' ]; then cd ./api; fi;

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - if [ $PROJECT == 'app' ];
    then yarn test;
    else yarn test:headless;
    fi;
  - yarn deploy;

# after_sucess:
#   - docker-compose build;
#   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $REGISTRY;
#   - docker-compose push;
