language: node_js
node_js:
  - '8'

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

env:
  - FOLDER=./
  - FOLDER=./api

cache:
  yarn: true
  directories:
    - node_modules

before_install:
  - cd $FOLDER

install:
  - yarn

script:
  - if [ $FOLDER == './api' ];
    then yarn test;
    else yarn test:headless;
    fi;
  - yarn deploy;

env:
  global: 
    after_sucess:
      - docker-compose build;
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $REGISTRY;
      - docker-compose push;
