language: node_js
env:
  global:
    - GET_ENV_VAR=./travis_get_variables.sh
    - AWS_ENV=$($GET_ENV_VAR $s3_domain_develop $s3_domain)
    - AWS_BUCKET=$($GET_ENV_VAR $s3_bucket_develop $s3_bucket)
node_js:
  - '8'

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules

install:
  - yarn

script:
  - yarn test:headless

after_success:
  - yarn deploy;
  - docker build -t bsalesc/shopping-list .;
  - docker tag bsalesc/shopping-list bsalesc/shopping-list:$(git rev-parse --short HEAD);
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push bsalesc/shopping-list;
