language: node_js
node_js:
  - '10'

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules
    - dist

jobs:
  include:
    - stage: Tests
      script:
        - yarn --cwd ./server
        - yarn --cwd ./server test
        - yarn --cwd ./client
        - yarn --cwd ./client test:headless
        - yarn coverage:echo | cat
        - yarn coverage
    - stage: Deploy and Publish
      script:
        - if [ $TRAVIS_BRANCH = "develop" ] & [ $TRAVIS_PULL_REQUEST = "false" ]; then docker-compose build; fi;
        - if [ $TRAVIS_BRANCH = "develop" ] & [ $TRAVIS_PULL_REQUEST = "false" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $REGISTRY; fi;
        - if [ $TRAVIS_BRANCH = "develop" ] & [ $TRAVIS_PULL_REQUEST = "false" ]; then docker-compose push; fi;
