language: node_js
node_js:
  - '8'

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules
    - dist

jobs:
  include:
    - stage: Test RESTapi
      script:
        - cd ./api
        - yarn
        - yarn test
    - stage: Test APP and Publish
      script:
        - cd ./app
        - yarn
        - yarn test:headless
        - yarn deploy
        - docker-compose build;
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $REGISTRY;
        - docker-compose push;

      # env:
      #   - PROJECT='app'
      #   - PROJECT='api'

      # before_install:
      #   - if [ $PROJECT == 'api' ]; then cd ./api; fi;

      # cache:
      #   yarn: true
      #   directories:
      #     - node_modules

      # install:
      #   - yarn

      # script:
      #   - if [ $PROJECT == 'api' ];
      #     then yarn test;
      #     else yarn test:headless;
      #     fi;
      #   - yarn deploy;

# after_sucess:
#   - docker-compose build;
#   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $REGISTRY;
#   - docker-compose push;
