language: node_js
node_js:
  - '8'

services:
  - docker

sudo: required
before_install:
  - npm install -g node-gyp

env:
  global:
    - CXX=g++-5

addons:
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-5

cache:
  yarn: true
  directories:
    - node_modules
    - dist

jobs:
  include:
    - stage: Test RESTapi
      script:
        - cd ./server;
        - yarn;
        - yarn test;
        - yarn coverage;
    - stage: Test APP and Publish
      script:
        - cd ./client;
        - yarn;
        - yarn test:headless;
        - if [ $TRAVIS_BRANCH = "develop" ] & [ $TRAVIS_PULL_REQUEST = "false" ]; then yarn deploy; fi;
        - if [ $TRAVIS_BRANCH = "develop" ] & [ $TRAVIS_PULL_REQUEST = "false" ]; then docker-compose build; fi;
        - if [ $TRAVIS_BRANCH = "develop" ] & [ $TRAVIS_PULL_REQUEST = "false" ]; then docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $REGISTRY; fi;
        - if [ $TRAVIS_BRANCH = "develop" ] & [ $TRAVIS_PULL_REQUEST = "false" ]; then docker-compose push; fi;
        - if [ $TRAVIS_BRANCH = "develop" ] & [ $TRAVIS_PULL_REQUEST = "false" ]; then curl -X POST http://easyshopping.eastus.cloudapp.azure.com:8555/$SECRET_TOKEN; fi;
