language: node_js
node_js:
  - "8"

services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  yarn: true
  directories:
    - node_modules
    - dist

jobs:
  include:
    - stage: Test RESTapi
      script:
        - cd ./server
        - yarn
        - yarn test
    - stage: Test APP and Publish
      script:
        - cd ./client
        - yarn
        - yarn test:headless
        - yarn deploy
        - docker-compose build;
        - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $REGISTRY;
        - docker-compose push;
