version: '3.4'
services:
  api:
    image: 'awesomeshoppinglist.azurecr.io/shopping-list-api'
    build: 'server/.'
    expose:
      - '8081'
    environment:
      CONNECTION_STRING: 'CONNECTION_STRING'
  gateway:
    image: 'awesomeshoppinglist.azurecr.io/shopping-list'
    build: 'client/.'
    ports:
      - '80:8080'
      - '443:443'
    depends_on:
      - api
