version: '3.4'
services:
  api:
    image: 'shoppyCart_api'
    build: 'server/.'
    expose:
      - '8081'
    environment:
      MONGO_CONNECTIONSTRING: 'mongodb://mongo:27017/shows'
      MONGO_USER: ''
      MONGO_PASS: ''
    depends_on:
      - mongo
    links:
      - mongo
  gateway:
    image: 'shoppyCart_gateway'
    build: 'client/.'
    ports:
      - '80:8080'
      - '443:443'
    depends_on:
      - api
  mongo:
    image: 'shoppyCart_mongo'
    build: 'mongo/.'
    volumes:
      - ./data/db:/data/db
    ports:
      - '27017:27017'
    command: --smallfiles
