version: '3.4'
services:
  api:
    image: 'bsalesc.azurecr.io/shoppycart_api'
    build: 'server/.'
    expose:
      - '8081'
    environment:
      MONGO_CONNECTIONSTRING: ${COSMO_DB_CONNECTIONSTRING}
      MONGO_USER: ${COSMO_DB_USER}
      MONGO_PASS: ${COSMO_DB_PASS}
  gateway:
    image: 'bsalesc.azurecr.io/shoppycart_gateway'
    build: 'client/.'
    ports:
      - '80:8080'
      - '443:443'
    depends_on:
      - api
