version: '3.1'
services:
  api:
    image: 'shopping-list-api'
    build: 'api/.'
    expose:
      - '8080'
  gateway:
    image: 'shopping-list'
    build: '.'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
    links:
      - dns:dnsmasq
  dns:
    build: ./dnsmasq
    ports:
      - '5353:53'
    links:
      - api

networks:
  default:
    driver: bridge
