version: 2.1

jobs:

  build:
    working_directory: ~/client
    docker:
      - image: circleci/node:10.9.0-browsers
    steps:
      # - restore_cache:
      #     name: Restore Yarn Package Cache
      #     keys:
      #       - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      # - save_cache:
      #     name: Save Yarn Package Cache
      #     key: yarn-packages-{{ checksum "yarn.lock" }}
      #     paths:
      #       - ~/.cache/yarn
      - run:
          name: Linting
          command: yarn lint
      - run:
          name: Testing
          command: yarn test:headless

  server_build:
    working_directory: ~/server
    docker:
      - image: circleci/node:10.9.0
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: Linting
          command: yarn tslint
      - run:
          name: Testing
          command: yarn test

  # deploy:
  #   working_directory: ~/
  #   steps:
  #       - docker-compose build
  #       - docker login -u="$registry_username" -p="$registry_password" $registry_server
  #       - docker-compose push


workflows:
    version: 2.1
    build_and_deploy:
        jobs:
            - build
            # - server_build
            # - deploy:
            #     requires:
            #         - client_build
            #         - server_build